### PR TITLE
added logo to readme

### PR DESCRIPTION
**Pull request by bluethefoxyt**
added a image aka the logo

### CODE REVIEW

**Comment by crmarsh** [comment]
Why not add the image file directly?

**Comment by kessanro** [comment]
@crmarsh good point
also the app is bugged on linux mint 18 kde
Uncaught exception:
 TypeError: Utils.setFocused is not a function
    at launchMainAppWindow (/usr/share/discord-canary/resources/app.asar/index.js:596:11)
    at SplashWindow.<anonymous> (/usr/share/discord-canary/resources/app.asar/index.js:608:16)
    at SplashWindow.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at SplashWindow.emit (events.js:185:7)
    at SplashWindow._launchMainWindow (/usr/share/discord-canary/resources/app.asar/SplashWindow.js:255:14)
    at Modules.<anonymous> (/usr/share/discord-canary/resources/app.asar/SplashWindow.js:64:15)
    at emitThree (events.js:121:20)
    at Modules.emit (events.js:194:7)
    at /usr/share/discord-canary/resources/app.asar/common/Modules.js:331:110
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
that is the error just saying

**Comment by crmarsh** [comment]
That is your bug in #164 right? Not sure what that has to do with adding a logo

**Comment by kessanro** [comment]
@crmarsh think i got distracted but still you need to fix that because it is bad it cant run

**Pull request closed without merging**
